[general]
import = [
    "~/.config/alacritty/themes/alacritty-theme/themes/github_dark_tritanopia.toml"
]

[window]
dimensions = { columns = 135, lines = 40 }
decorations = "Full"
# padding.x = 15
# padding.y = 15
# opacity = 0.7
# blur = true
option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 14

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
