[general]
import = [
  "github_dark_custom.toml",
  "alacritty-local.toml"
]

[window]
dimensions = { columns = 135, lines = 40 }
decorations = "Full"
startup_mode = "Windowed"
decorations_theme_variant = "Dark"
dynamic_title = false

padding.x = 10
padding.y = 10
option_as_alt = "Both"


[terminal]

shell = { program = "wsl.exe", args = ["~"] }

[selection]
save_to_clipboard = true


[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Light" }

bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
# size = 12 # default
[font.offset]
x = 0
y = -1

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]


