# github Alacritty Colors

# Default colors
[colors.primary]
background = '#0d1117'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black   = '#484f58'
red     = '#ff7b72'
green   = '#3fb950'
yellow  = '#d29922'
blue    = '#58a6ff'
magenta = '#bc8cff'
cyan    = '#39c5cf'
white   = '#b1bac4'

# Bright colors
[colors.bright]
black   = '#6e7681'
red     = '#ffa198'
green   = '#56d364'
yellow  = '#e3b341'
blue    = '#79c0ff'
magenta = '#d2a8ff'
cyan    = '#56d4dd'
white   = '#f0f6fc'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#ffa198'


[window]
dimensions = { columns = 130, lines = 45 }
padding = { x = 12, y = 12 }
dynamic_padding = true
decorations = "Full"
option_as_alt = "Both"

[font]
size = 13

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
