#! /bin/sh

INTERNAL_MONITOR="eDP-1"
EXTERNAL_MONITOR="HDMI-1"

for desktop in $(bspc query -D); do
    bspc desktop "$desktop" --remove
done

xrandr --output "$INTERNAL_MONITOR" --scale 0.75x0.75
if xrandr | grep "^${EXTERNAL_MONITOR} connected" >/dev/null; then
    xrandr --output "$EXTERNAL_MONITOR" --scale 1.8x1.8 --auto --right-of "$INTERNAL_MONITOR"
    bspc monitor "$EXTERNAL_MONITOR" -d 1 2 3 4 5
    bspc monitor "$INTERNAL_MONITOR" -d 6 7 8 9 10
    bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
else
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 10
fi

pgrep -x sxhkd > /dev/null || sxhkd &
picom --config ~/.config/picom/picom.conf &
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10

xrdb ~/.Xresources
bspc config focus_follows_pointer true
bspc config focused_border_color "#746DFE"  # цвет рамки у активного окна
bspc config normal_border_color "#7DCFFF"   # цвет рамки у неактивного окна
bspc config presel_border_color "#1AD29F"   # цвет рамки при предварительном выборе
bspc config urgent_border_color "#F8F8F2"   # цвет рамки для окна с urgent-состоянием
# модальные окна
bspc rule -a Xdialog state=floating center=on

# feh --bg-scale "$LOCKSCREEN_IMAGE" &
feh --bg-fill "$LOCKSCREEN_IMAGE" &
#
# пробуждение
case $(ps -p 1 -o comm=) in
  systemd)
    systemctl --user import-environment DISPLAY XAUTHORITY
    ;;
esac
# Рестарт компонентов после пробуждения
systemctl --user restart picom polybar &> /dev/null
pkill -USR1 picom &> /dev/null

bspc config window_gap           2
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config border_width 2

xsetroot -cursor_name left_ptr &
# xsetroot -solid "#222222" &

# mouse
bspc config pointer_modifier mod4          # Обычно mod4 - клавиша Super (Win)
bspc config pointer_action1 move            # ЛКМ - перемещение окна
bspc config pointer_action2 resize_side     # СКМ - изменение размера с боков
bspc config pointer_action3 resize_corner   # ПКМ - изменение размера с углов


$HOME/.config/polybar/launch.sh &
# xsettingsd &
xss-lock -- slock &
flameshot &
touchegg &
udiskie -a -n -t &
dunst &
alacritty &

