#! /bin/sh

# Создаём симлинк для текущей схемы
ln -sf ~/.config/colors/schemes/$(cat ~/.config/colors/current_scheme).conf ~/.config/colors/current.conf

# Загрузка цветовой схемы
export COLOR_SCHEME=$(cat ~/.config/colors/current_scheme)
source ~/.config/colors/current.conf

# Обновляем цвета BSPWM
~/.config/bspwm/bin/update-colors

INTERNAL_MONITOR="eDP-1"
EXTERNAL_MONITOR="HDMI-1"

for desktop in $(bspc query -D); do
    bspc desktop "$desktop" --remove
done

xrandr --output "$INTERNAL_MONITOR" --scale 0.75x0.75
if xrandr | grep "^${EXTERNAL_MONITOR} connected" >/dev/null; then
    xrandr --output "$EXTERNAL_MONITOR" --scale 1.5x1.5 --auto --right-of "$INTERNAL_MONITOR"
    bspc monitor "$EXTERNAL_MONITOR" -d 1 2 3 4 5
    bspc monitor "$INTERNAL_MONITOR" -d 6 7 8 9 10
    bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
else
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 10
fi

pgrep -x sxhkd > /dev/null || sxhkd &
picom --config ~/.config/picom/picom.conf &

xrdb ~/.Xresources
bspc rule -a Xdialog state=floating center=on

feh --bg-fill "$LOCKSCREEN_IMAGE" &
case $(ps -p 1 -o comm=) in
  systemd)
    systemctl --user import-environment DISPLAY XAUTHORITY
    ;;
esac
systemctl --user restart picom polybar &> /dev/null
pkill -USR1 picom &> /dev/null

# звук при запуске
canberra-gtk-play -i service-login

bspc config focus_follows_pointer true
bspc config window_gap           2
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config border_width 2

xsetroot -cursor_name left_ptr &

$HOME/.config/polybar/launch_separate.sh &
xss-lock -- $HOME/.config/bspwm/bin/lock &
flameshot &
touchegg &
udiskie -a -n -t &
dunst &
alacritty &
