backend = "glx"

vsync = true
unredir-if-possible = true

fading = true
fade-in-step = 0.03
fade-out-step = 0.03
fade-delta = 4

shadow = true
shadow-radius = 7
shadow-offset-x = -7
shadow-offset-y = -7
shadow-opacity = 0.6
shadow-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'rofi'",
  "class_g = 'Dunst'",
  "class_g = 'slock'",
  "_NET_WM_STATE@ = '_NET_WM_STATE_ABOVE'"
]

blur-background = false

corner-radius = 15;
round-borders = 1
detect-client-opacity = true
detect-transient = true
detect-rounded-corners = true

rounded-corners-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'Dunst'",
  "class_g = 'slock'",
  "window_type = 'dock'"
]

wintypes = {
  tooltip = { fade = false; shadow = false; };
  dock = { shadow = false; corner-radius = 0; };
  popup_menu = { shadow = false; };
  dropdown_menu = { shadow = false; };
  menu = { shadow = false; };
}
