#! /bin/sh

# Создаём симлинк для текущей схемы
ln -sf ~/.config/colors/schemes/$(cat ~/.config/colors/current_scheme).conf ~/.config/colors/current.conf

# Загрузка цветовой схемы
ln -sf ~/.config/colors/schemes/$(cat ~/.config/colors/current_scheme).conf ~/.config/colors/current.conf
~/.config/bspwm/bin/update-colors
export COLOR_SCHEME=$(cat ~/.config/colors/current_scheme)

# Обновляем цвета BSPWM
~/.config/bspwm/bin/update-colors

source ~/.config/bspwm/monitors.sh

pgrep -x sxhkd > /dev/null || sxhkd &

for desktop in $(bspc query -D); do
    bspc desktop "$desktop" --remove
done

xrandr --output "$INTERNAL_MONITOR" --scale 1x1
if xrandr | grep "^${EXTERNAL_MONITOR} connected" >/dev/null; then
    xrandr --output "$EXTERNAL_MONITOR" --scale 1x1 --auto --right-of "$INTERNAL_MONITOR"
    xrandr --output "$INTERNAL_MONITOR" --primary
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3
    bspc monitor "$EXTERNAL_MONITOR" -d 4 5 6
    bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
else
    xrandr --output "$INTERNAL_MONITOR" --primary
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6
fi

bspc rule -a Alacritty desktop='^1' follow=on
alacritty &

picom --config ~/.config/picom/picom.conf &

bspc rule -a Xdialog state=floating center=on

feh --bg-fill "$LOCKSCREEN_IMAGE" &
case $(ps -p 1 -o comm=) in
  systemd)
    systemctl --user import-environment DISPLAY XAUTHORITY
    ;;
esac
systemctl --user restart picom polybar &> /dev/null
pkill -USR1 picom &> /dev/null

# звук при запуске
canberra-gtk-play -i service-login

bspc config focus_follows_pointer false
bspc config window_gap           2
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2' state=tiled follow=on
bspc rule -a DBeaver desktop='^1' state=tiled follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc config border_width 4

xsetroot -cursor_name left_ptr &

$HOME/.config/polybar/launch_separate.sh &
flameshot &
# touchegg &
udiskie -a -n -t &
dunst &

# скорость мыши
xinput set-prop 14 'libinput Accel Speed' -0.8

exec bspwm
