#!/bin/sh

#================== ЦВЕТА ==================
ln -sf ~/.config/colors/schemes/$(cat ~/.config/colors/current_scheme).conf ~/.config/colors/current.conf
export COLOR_SCHEME=$(cat ~/.config/colors/current_scheme)
~/.config/bspwm/bin/update-colors

#================== МОНИТОРЫ ===============
source ~/.config/bspwm/monitors.sh

#================== BSPWM НАСТРОЙКИ =========
# for desktop in $(bspc query -D); do
#     bspc desktop "$desktop" --remove
# done

xrandr --output "$INTERNAL_MONITOR" --scale 1x1
if xrandr | grep "^${EXTERNAL_MONITOR} connected" >/dev/null; then
    xrandr --output "$EXTERNAL_MONITOR" --scale 1x1 --auto --right-of "$INTERNAL_MONITOR"
    xrandr --output "$INTERNAL_MONITOR" --primary
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3
    bspc monitor "$EXTERNAL_MONITOR" -d 4 5 6
    bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
else
    xrandr --output "$INTERNAL_MONITOR" --primary
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6
fi

#================== ПРАВИЛА ОКОН ===========
bspc rule -a Alacritty desktop='^1' follow=on
bspc rule -a DBeaver desktop='^1' state=tiled follow=on
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a TelegramDesktop desktop='^3' follow=on
bspc rule -a Mattermost desktop='^3' follow=on
bspc rule -a firefox desktop='^4' state=tiled follow=on
bspc rule -a libreoffice-startcenter desktop='^4' state=tiled follow=on
bspc rule -a Org.gnome.Evolution desktop='^5' state=tiled follow=on
bspc rule -a ktalk desktop='^5' state=tiled follow=on
bspc rule -a org.remmina.Remmina desktop='^6' state=tiled follow=on

bspc rule -a Xdialog state=floating center=on layer=above
bspc rule -a Dialog state=floating center=on layer=above
bspc rule -a "*Preferences*" state=floating center=on layer=above
bspc rule -a "*properties*" state=floating center=on layer=above

#================== AUTOSTART ==============
pgrep -x sxhkd > /dev/null || sxhkd -m -1 &
feh --bg-fill "$LOCKSCREEN_IMAGE" &
$HOME/.config/polybar/launch_separate.sh &
flameshot &
udiskie -a -n -t &
dunst &

#================== BSPWM CONFIG ===========
bspc config focus_follows_pointer false
bspc config window_gap           6
bspc config split_ratio          0.52
bspc config automatic_scheme     spiral
bspc config border_width         4
bspc config borderless_monocle   true
bspc config gapless_monocle      false

#================== СИСТЕМА ================
xsetroot -cursor_name left_ptr &
xinput set-prop 14 'libinput Accel Speed' -0.8

case $(ps -p 1 -o comm=) in
  systemd)
    systemctl --user import-environment DISPLAY XAUTHORITY
    systemctl --user restart picom polybar &> /dev/null
    ;;
esac
# pkill -USR1 picom &> /dev/null
canberra-gtk-play -i service-login
picom --config ~/.config/picom/picom.conf &
# exec bspwm
