[colors]
background     = #282C34
background-alt = #21252B00
foreground     = #ABB2BF
primary        = #E7C787
blue           = #61AFEF
secondary      = #C678DD
alert          = #FF75A0
disabled       = #5C6370
green          = #98C379
pink           = #FF75A0
purple         = #DE98FD
cyan           = #56B6C2
orange         = #FCA2AA
red            = #E06C75
yellow         = #E7C787
white          = #FFFFFF
background-alt2= #21252B

