[colors]
background     = #0D1119
background-alt = #0A0D14AA
foreground     = #C0CAF5
primary        = #7AA2F7
blue           = #7AA2F7
secondary      = #BB9AF7
alert          = #F7768E
disabled       = #565F89
green          = #9ECE6A
pink           = #F7768E
purple         = #BB9AF7
cyan           = #7DCFFF
orange         = #FF9E64
red            = #F7768E
yellow         = #E0AF68
white          = #C0CAF5
background-alt2= #0A0D14
