[colors.primary]
background = '#131318'
foreground = '#e4e1e9'

[colors.cursor]
text = '#131318'
cursor = '#e4e1e9'

[colors.vi_mode_cursor]
text = '#131318'
cursor = '#c1c1ff'

[colors.search.matches]
foreground = '#47464f'
background = '#e9b9d2'

[colors.search.focused_match]
foreground = '#47464f'
background = '#c1c1ff'

[colors.footer_bar]
foreground = '#47464f'
background = '#e4e1e9'

[colors.hints.start]
foreground = '#47464f'
background = '#c6c4dd'

[colors.hints.end]
foreground = '#47464f'
background = '#c6c4dd'

[colors.selection]
text = '#c8c5d0'
background = '#47464f'


[colors.normal]
black   = '#47464f'
red     = '#ffb4ab'
green   = '#c1c1ff'
yellow  = '#c6c4dd'
blue    = '#e9b9d2'
magenta = '#c1c1ff'
cyan    = '#c6c4dd'
white   = '#e4e1e9'


[colors.bright]
black   = '#918f9a'
red     = '#ffb4ab'
green   = '#c1c1ff'
yellow  = '#c6c4dd'
blue    = '#e9b9d2'
magenta = '#c1c1ff'
cyan    = '#c6c4dd'
white   = '#e4e1e9'


[colors.dim]
black   = '#47464f'
red     = '#ffb4ab'
green   = '#c1c1ff'
yellow  = '#c6c4dd'
blue    = '#e9b9d2'
magenta = '#c1c1ff'
cyan    = '#c6c4dd'
white   = '#e4e1e9'
