# ~/.config/tmux/themes/ayu_dark.conf

set -g status-style "fg=#FFFFFF,bg=default"
set -g status-left "#[fg=#ff9445]   #[fg=#FFFFFF] #S "
set -g status-left-length 20
set -g status-right "#[fg=#ff9445]  %H:%M #[fg=#ff9445]  %d-%b-%Y "
set -g status-right-length 50

set -g window-status-style "fg=#686868,bg=default"
set -g window-status-current-style "fg=#ff9445,bold,bg=default"
set -g window-status-format "#I:#W "
set -g window-status-current-format "#I:#W "

set -g pane-border-style "fg=#686868"
set -g pane-active-border-style "fg=#ff9445"

set -g display-panes-colour "#FFFFFF"
set -g display-panes-active-colour "#ff9445"

set -g message-style "fg=#FFFFFF,bg=default"
set -g message-command-style "fg=#FFFFFF,bg=default"

set -g mode-style "fg=#ff9445,bg=default"
