# ~/.config/tmux/themes/dracula.conf

set -g status-style "fg=#E6E6E6,bg=default"
set -g status-left "#[fg=#746DFE]   #[fg=#E6E6E6] #S "
set -g status-left-length 20
set -g status-right "#[fg=#746DFE]  %H:%M #[fg=#746DFE]  %d-%b-%Y "
set -g status-right-length 50

set -g window-status-style "fg=#424868,bg=default"
set -g window-status-current-style "fg=#746DFE,bold,bg=default"
set -g window-status-format "#I:#W "
set -g window-status-current-format "#I:#W "

set -g pane-border-style "fg=#424868"
set -g pane-active-border-style "fg=#746DFE"

set -g display-panes-colour "#E6E6E6"
set -g display-panes-active-colour "#746DFE"

set -g message-style "fg=#E6E6E6,bg=default"
set -g message-command-style "fg=#E6E6E6,bg=default"

set -g mode-style "fg=#746DFE,bg=default"
