# ~/.config/tmux/themes/noctalia.conf

set -g status-style "fg=#dee3e5,bg=default"
set -g status-left "#[fg=#83d2e4]   #[fg=#dee3e5] #S "
set -g status-left-length 20
set -g status-right "#[fg=#83d2e4]  %H:%M #[fg=#83d2e4]  %d-%b-%Y "
set -g status-right-length 50

set -g window-status-style "fg=#3f484b,bg=default"
set -g window-status-current-style "fg=#83d2e4,bold,bg=default"
set -g window-status-format "#I:#W "
set -g window-status-current-format "#I:#W "

set -g pane-border-style "fg=#3f484b"
set -g pane-active-border-style "fg=#83d2e4"

set -g display-panes-colour "#dee3e5"
set -g display-panes-active-colour "#83d2e4"

set -g message-style "fg=#dee3e5,bg=default"
set -g message-command-style "fg=#dee3e5,bg=default"

set -g mode-style "fg=#83d2e4,bg=default"
