# ~/.config/tmux/themes/one_dark.conf

set -g status-style "fg=#ABB2BF,bg=default"
set -g status-left "#[fg=#E7C787]   #[fg=#ABB2BF] #S "
set -g status-left-length 20
set -g status-right "#[fg=#E7C787]  %H:%M #[fg=#E7C787]  %d-%b-%Y "
set -g status-right-length 50

set -g window-status-style "fg=#5C6370,bg=default"
set -g window-status-current-style "fg=#E7C787,bold,bg=default"
set -g window-status-format "#I:#W "
set -g window-status-current-format "#I:#W "

set -g pane-border-style "fg=#5C6370"
set -g pane-active-border-style "fg=#E7C787"

set -g display-panes-colour "#ABB2BF"
set -g display-panes-active-colour "#E7C787"

set -g message-style "fg=#ABB2BF,bg=default"
set -g message-command-style "fg=#ABB2BF,bg=default"

set -g mode-style "fg=#E7C787,bg=default"
