# ~/.config/tmux/themes/tokyo_night.conf

set -g status-style "fg=#A9B1D6,bg=default"
set -g status-left "#[fg=#7aa2f7]   #[fg=#A9B1D6] #S "
set -g status-left-length 20
set -g status-right "#[fg=#7aa2f7]  %H:%M #[fg=#7aa2f7]  %d-%b-%Y "
set -g status-right-length 50

set -g window-status-style "fg=#414868,bg=default"
set -g window-status-current-style "fg=#7aa2f7,bold,bg=default"
set -g window-status-format "#I:#W "
set -g window-status-current-format "#I:#W "

set -g pane-border-style "fg=#414868"
set -g pane-active-border-style "fg=#7aa2f7"

set -g display-panes-colour "#A9B1D6"
set -g display-panes-active-colour "#7aa2f7"

set -g message-style "fg=#A9B1D6,bg=default"
set -g message-command-style "fg=#A9B1D6,bg=default"

set -g mode-style "fg=#7aa2f7,bg=default"
