# ~/.config/tmux/themes/tokyo_dark.conf

set -g status-style "fg=#C0CAF5,bg=default"
set -g status-left "#[fg=#7AA2F7]   #[fg=#C0CAF5] #S "
set -g status-left-length 20
set -g status-right "#[fg=#7AA2F7]  %H:%M #[fg=#7AA2F7]  %d-%b-%Y "
set -g status-right-length 50

set -g window-status-style "fg=#565F89,bg=default"
set -g window-status-current-style "fg=#7AA2F7,bold,bg=default"
set -g window-status-format "#I:#W "
set -g window-status-current-format "#I:#W "

set -g pane-border-style "fg=#565F89"
set -g pane-active-border-style "fg=#7AA2F7"

set -g display-panes-colour "#C0CAF5"
set -g display-panes-active-colour "#7AA2F7"

set -g message-style "fg=#C0CAF5,bg=default"
set -g message-command-style "fg=#C0CAF5,bg=default"

set -g mode-style "fg=#7AA2F7,bg=default"
