[global]
background = "{{background}}"
frame_color = "{{primary}}"
frame_width = {{frame_width}}
corner_radius = {{corner_radius}}
foreground = "{{foreground}}"
font = "{{font}}"
width = {{width}}
origin = top-right
offset = ({{offset_x}}, {{offset_y}})

[urgency_normal]
background = "{{background}}"
foreground = "{{foreground}}"
timeout = 5

[urgency_low]
background = "{{disabled}}"
foreground = "{{foreground}}"
timeout = 3

[urgency_critical]
background = "{{alert}}"
foreground = "{{foreground}}"
timeout = 0

[play_sound]
summary = "*"
script = $HOME/.config/dunst/src/dunst-sound